# = = = = = = = = = = #
#    A L I A S E S    #
# = = = = = = = = = = #
alias open="xdg-open"
alias py="python"
alias ls="ls --color=auto -p"
alias grep="grep --color=auto"
alias diff="diff --color=auto"
alias ip="ip -color=auto"
alias nano="nano -l"
alias cal="cal -m"
alias rm="trash-put"
alias sudo="doas"
alias less="less -RN"
alias wget="wget --hsts-file=$XDG_CACHE_HOME/wget-hsts"
alias cht.sh="curl https://cht.sh/\$1"
alias zathura="zathura --fork"
alias nnn="nnn -e"
alias pfetch="fastfetch -c ~/.config/fastfetch/pfetch.jsonc"
alias neofetch="fastfetch -c ~/.config/fastfetch/neofetch.jsonc"
alias nsxiv="nsxiv-rifle"
alias tmux="tmux -2"
alias sc-im="TERM=xterm-256color sc-im"

alias ramfetch="dmidecode -t 17"
alias resrs="xrandr -s 1366x768"

alias tint="tint -s -n -d"
alias my-ip="curl ifconfig.me/ip; echo ''"
alias weather="curl wttr.in/rs"
alias jar="java -jar"

alias dosbox="dosbox -conf $XDG_CONFIG_HOME/dosbox/dosbox.conf"
alias xbindkeys="xbindkeys -f $XDG_CONFIG_HOME/xbindkeys/config"
alias mbsync="mbsync -c $XDG_CONFIG_HOME/isync/mbsyncrc"
alias yarn="yarn --use-yarnrc $XDG_CONFIG_HOME/yarn/config"
alias pidgin="pidgin --config=$XDG_DATA_HOME/purple"
alias curl-img="curl_img"
alias fzf-history="fzf_history"
alias fceux="fceux -style fusion -platformtheme generic"
