conky.config = {
    alignment = 'top_right',
    background = false,
    double_buffer = true,
    font = 'DejaVu Sans Mono:size=12',
    gap_x = 60,
    gap_y = 60,
    no_buffers = true,
    out_to_x = true,
    own_window = true,
    own_window_class = 'Conky',
    own_window_type = 'override',
    own_window_transparent = false,
    own_window_argb_visual = true,
    own_window_argb_value = 0,
    update_interval = 1800,
    use_xft = true,
}

conky.text = [[
${execi 3600 ~/.config/conky/tickkr.sh QDVE.DE}
${hr}
${execi 3600 ~/.config/conky/tickkr.sh SXR8.DE}
]]
