[general]
    live_config_reload = true
    import = [
        "keybinds.toml",
        "colors.toml",
    ]

[scrolling]
    history = 10000
    multiplier = 10

[selection]
    save_to_clipboard = true
    semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
    opacity = 0.9
    padding =    { x = 4,    y = 4 }
    position =   { x = 275,  y = 150 }
    dimensions = { columns = 100, lines = 25 }

[font]
    size = 9.0
    offset =        { x = 0, y = 1 }
    glyph_offset =  { x = 0, y = 0 }

    normal =        { family = "Source Code Pro",   style = "Medium" }
    bold =          { family = "Source Code Pro",   style = "Bold" }
    italic =        { family = "Source Code Pro",   style = "Italic" }
    bold_italic =   { family = "Source Code Pro",   style = "Bold Italic" }
